name: Frontend CI/CD Pipeline

on:
  push:
    paths:
      - 'front-end/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync S3 Bucket
      run: |
        aws s3 sync front-end/ s3://your-s3-bucket-name/ --delete

    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
