name: Frontend Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Sync S3 bucket
        working-directory: front-end
        run: |
          aws s3 sync . s3://your-s3-bucket-name --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id your-distribution-id --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ redacted }}
          AWS_SECRET_ACCESS_KEY: ${{ redacted}}
